//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElyonComunicator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codificaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codificaciones()
        {
            this.Gestiones = new HashSet<Gestiones>();
        }
    
        public int codID { get; set; }
        public string codTipoRegistro { get; set; }
        public string codEstado { get; set; }
        public string codTipoContacto { get; set; }
        public string codResultado { get; set; }
        public string codTipoLlamada { get; set; }
        public string codRelanzado { get; set; }
        public string codArea { get; set; }
        public string codModulo { get; set; }
        public string codActivo { get; set; }
        public Nullable<int> codCtaID { get; set; }
        public string codAsterisk { get; set; }
        public string codMedio { get; set; }
        public Nullable<int> codDiasMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestiones> Gestiones { get; set; }
    }
}
