//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElyonComunicator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestiones
    {
        public int gID { get; set; }
        public Nullable<int> areaID { get; set; }
        public Nullable<int> codGestionID { get; set; }
        public Nullable<int> agenteID { get; set; }
        public Nullable<int> baseID { get; set; }
        public Nullable<int> tramoControID { get; set; }
        public Nullable<int> areaDerivadaID { get; set; }
        public Nullable<int> estadoResueltoID { get; set; }
        public Nullable<int> clientesID { get; set; }
        public Nullable<System.DateTime> fechaGestion { get; set; }
        public Nullable<System.DateTime> fechaVll { get; set; }
        public string comentario { get; set; }
        public Nullable<int> nroSocio { get; set; }
        public Nullable<int> nroCredito { get; set; }
        public string nroTC { get; set; }
        public Nullable<int> diasMora { get; set; }
        public Nullable<int> montoMora { get; set; }
        public Nullable<int> productoID { get; set; }
        public string telefonoRef { get; set; }
        public string seguimiento { get; set; }
        public Nullable<System.DateTime> fechaResuelto { get; set; }
        public string comentario2 { get; set; }
        public string nroCI { get; set; }
        public string nombreCliente { get; set; }
        public Nullable<int> id_canal { get; set; }
        public Nullable<int> sucID { get; set; }
        public string solicobrador { get; set; }
        public Nullable<int> ctaId { get; set; }
    
        public virtual Codificaciones Codificaciones { get; set; }

        internal void set_insertaGestionesExternas(int v, int v1)
        {
            throw new NotImplementedException();
        }

        internal void set_InsertaGestiones(int v1, int v2, int v3, string obs)
        {
            throw new NotImplementedException();
        }
    }
}
